on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  specs:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Set Git Preferences
        run: |
          git config --global user.name 'Spec Runner'
          git config --global user.email 'git@github.com'
      - name: Run tests
        run: crystal spec
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Format source code
        run: crystal tool format --check
